#!/bin/bash
# To calculate multibamsummary for pearson correlation check
#BSUB -J myjobMPI
#BSUB -n 12
#BSUB -R span[ptile=12]
#BSUB -R rusage[mem=12]
#BSUB -W 20:00
#BSUB -o %J.stdout
#BSUB -eo %J.stderr

#multiBamSummary bins  --ignoreDuplicates --bamfiles  *MPP*bam *MPP*bam *CLP*bam *GMP*bam *MEP*bam *CMP*bam  -bs 10000 -p 12     -o humanHsc03232023_2.npz
