#!/bin/bash
# To plot correlation of different bam file
#BSUB -J myjobMPI
#BSUB -n 12
#BSUB -R span[ptile=12]
#BSUB -R rusage[mem=1]
#BSUB -W 20:00
#BSUB -o %J.stdout
#BSUB -eo %J.stderr
#plotCorrelation -in humanhscatacandrloopcorrelation.npz --cormethod spearman --skipzeros --plottitle "humanhscatacandrloopcorrelation.npz" \
#--whatToPlot heatmap --colorMap RdYlBu --plotNumbers -o  humanHscAtacAndRloopCorrelation.npz.pdf  --outFileCorMatrix     humanHscAtacAndRloopCorrelation.npz.tab
